### ISSUE TITLE
Too many redirects Error

### ISSUE THREAD

**Issue by ollie-iterators** [internetarchive/warcprox#125]
When trying to save http://www.alumni.weber.edu/ to see if https://github.com/internetarchive/warcprox/pull/124 fixed the issue for that site, I noticed that the save still did not work for that site, because it said there were "too many redirects". 

This is a screen shot of the error that happened for the site.
![Screen Shot 2019-04-14 at 10 10 40 AM](https://user-images.githubusercontent.com/46904826/56094056-b620f380-5e9d-11e9-9f7d-4c115b2e8fb3.png)

**Comment by nlevitt** [comment]
I don't think this is a warcprox issue. I've passed along your report to interested parties.
