### ISSUE TITLE
v.2.5.1 - Watching Youtube over warcprox not working

### ISSUE THREAD

**Issue by yacylover** [internetarchive/warcprox#195]
Hi,

I just installed warcprox 2.5.1 via command pip install git+https://github.com/internetarchive/warcprox.git

I found out that Youtube playback isn't working. Video page loads very well but playback won't start :-(

Please fix

Kind regards

Steve

**Comment by galgeek** [comment]
youtube captures that offer good youtube playback depend much more on the crawler used with warcprox and then the replay software. I'd check those first.

**Comment by yacylover** [comment]
Thank you very much. Yes, the archived youtube video at this URL works very well. I guess I have some certificate issues (the log shows that) that cause my playback/capture problem. What Linux distribution do you recommend running warcprox on?

**Comment by TheTechRobo** [comment]
Ensure that your browser has whatever CA certificate that Warcprox generated (or whatever one you gave it to use) set as 'trusted'.

**Comment by yacylover** [comment]
Thank you very much. Yeah, I did that a few weeks ago (Imported it in Firefox own keystore. But the behavior in browser was very strange: Youtube page loads very well without any cert warnings but the player stuck in an infinite loop at the very beginning of the video at 0:00. Warcprox logs showed some cert issues. But now I tested again under Fedora Linux 27 and the issues are gone.
