### ISSUE TITLE
Disown fork parent

### ISSUE THREAD

**Issue by chbrown** [internetarchive/warcprox#20]
Seeing that this repo has pretty much completely diverged from nlevitt's, and thence allfro's, and that GitHub forks get second-class functionality... (E.g., when I try to figure out what format `warcprox-dedup.db` is, via <https://github.com/internetarchive/warcprox/search?q=warcprox-dedup.db&type=Code>
![Link to screenshot](https://pbs.twimg.com/media/CvgZBWKUEAA_X1K.jpg))

...might you consider unforking it, i.e., making it its own first class repo?

**Comment by nlevitt** [comment]
Yeah I do want to do that. Seems the only way to do that (without losing issues, PRs, stars, etc) is to contact github support, so I've done that. Awaiting response.

**Comment by chbrown** [comment]
I had to do that a couple years ago for a fork that outgrew its parent; I'd've figured they'd've made that a user feature by now, but guess not :( — still, they were pretty quick to flip that switch once I emailed support. Thanks!

**Comment by nlevitt** [comment]
It's done!
