### ISSUE TITLE
The Installation of the pip Package Requires Root Privileges

### ISSUE THREAD

**Issue by martinvahi** [internetarchive/warcprox#22]
If the apt-get based dependencies are met, then users should be able to install pip packages without having any root access. [Log file](http://temporary.softf1.com/2017/bugs/2017_02_08_github_bugreport_internetarchive_warcprox_pip.log.txt). Console output:

    warc_librarian@acstorage3334:/home $ cd ~
    warc_librarian@acstorage3334:~ $ pip install warcprox
    Downloading/unpacking warcprox
      Downloading warcprox-2.0.tar.gz
      Running setup.py (path:/tmp/pip-build-TimZHe/warcprox/setup.py) egg_info for package warcprox
        
    Downloading/unpacking certauth>=1.1.0 (from warcprox)
      Downloading certauth-1.1.3.tar.gz
      Running setup.py (path:/tmp/pip-build-TimZHe/certauth/setup.py) egg_info for package certauth
        
    Downloading/unpacking warctools (from warcprox)
      Downloading warctools-4.10.0.tar.gz
      Running setup.py (path:/tmp/pip-build-TimZHe/warctools/setup.py) egg_info for package warctools
        
    Downloading/unpacking kafka-python>=1.0.1 (from warcprox)
      Downloading kafka_python-1.3.2-py2.py3-none-any.whl (195kB): 195kB downloaded
    Downloading/unpacking surt>=0.3b4 (from warcprox)
      Downloading surt-0.3.0.tar.gz
      Running setup.py (path:/tmp/pip-build-TimZHe/surt/setup.py) egg_info for package surt
        
        warning: no files found matching '*.txt'
        warning: no files found matching '*.md'
    Downloading/unpacking rethinkstuff (from warcprox)
      Downloading rethinkstuff-0.1.7.tar.gz
      Running setup.py (path:/tmp/pip-build-TimZHe/rethinkstuff/setup.py) egg_info for package rethinkstuff
        
    Downloading/unpacking PySocks (from warcprox)
      Downloading PySocks-1.6.6.tar.gz (282kB): 282kB downloaded
      Running setup.py (path:/tmp/pip-build-TimZHe/PySocks/setup.py) egg_info for package PySocks
        
    Downloading/unpacking futures (from warcprox)
      Downloading futures-3.0.5-py2-none-any.whl
    Requirement already satisfied (use --upgrade to upgrade): pyopenssl in /usr/lib/python2.7/dist-packages (from certauth>=1.1.0->warcprox)
    Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from surt>=0.3b4->warcprox)
    Downloading/unpacking tldextract>=2.0 (from surt>=0.3b4->warcprox)
      Downloading tldextract-2.0.2-py2.py3-none-any.whl (52kB): 52kB downloaded
    Downloading/unpacking rethinkdb (from rethinkstuff->warcprox)
      Downloading rethinkdb-2.3.0.post6.tar.gz (118kB): 118kB downloaded
      Running setup.py (path:/tmp/pip-build-TimZHe/rethinkdb/setup.py) egg_info for package rethinkdb
        
    Downloading/unpacking idna (from tldextract>=2.0->surt>=0.3b4->warcprox)
      Downloading idna-2.2-py2.py3-none-any.whl (55kB): 55kB downloaded
    Requirement already satisfied (use --upgrade to upgrade): requests>=2.1.0 in /usr/lib/python2.7/dist-packages (from tldextract>=2.0->surt>=0.3b4->warcprox)
    Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/dist-packages (from tldextract>=2.0->surt>=0.3b4->warcprox)
    Downloading/unpacking requests-file>=1.4 (from tldextract>=2.0->surt>=0.3b4->warcprox)
      Downloading requests_file-1.4.1-py2.py3-none-any.whl
    Installing collected packages: warcprox, certauth, warctools, kafka-python, surt, rethinkstuff, PySocks, futures, tldextract, rethinkdb, idna, requests-file
      Running setup.py install for warcprox
        error: could not create '/usr/local/lib/python2.7/dist-packages/warcprox': Permission denied
        Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-TimZHe/warcprox/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-hWq6DN-record/install-record.txt --single-version-externally-managed --compile:
        running install
    
    running build
    
    running build_py
    
    creating build
    
    creating build/lib.linux-armv7l-2.7
    
    creating build/lib.linux-armv7l-2.7/warcprox
    
    copying warcprox/kafkafeed.py -> build/lib.linux-armv7l-2.7/warcprox
    
    copying warcprox/mitmproxy.py -> build/lib.linux-armv7l-2.7/warcprox
    
    copying warcprox/stats.py -> build/lib.linux-armv7l-2.7/warcprox
    
    copying warcprox/writerthread.py -> build/lib.linux-armv7l-2.7/warcprox
    
    copying warcprox/playback.py -> build/lib.linux-armv7l-2.7/warcprox
    
    copying warcprox/dedup.py -> build/lib.linux-armv7l-2.7/warcprox
    
    copying warcprox/bigtable.py -> build/lib.linux-armv7l-2.7/warcprox
    
    copying warcprox/dump_anydbm.py -> build/lib.linux-armv7l-2.7/warcprox
    
    copying warcprox/__init__.py -> build/lib.linux-armv7l-2.7/warcprox
    
    copying warcprox/warcproxy.py -> build/lib.linux-armv7l-2.7/warcprox
    
    copying warcprox/controller.py -> build/lib.linux-armv7l-2.7/warcprox
    
    copying warcprox/writer.py -> build/lib.linux-armv7l-2.7/warcprox
    
    copying warcprox/warc.py -> build/lib.linux-armv7l-2.7/warcprox
    
    copying warcprox/main.py -> build/lib.linux-armv7l-2.7/warcprox
    
    running install_lib
    
    creating /usr/local/lib/python2.7/dist-packages/warcprox
    
    error: could not create '/usr/local/lib/python2.7/dist-packages/warcprox': Permission denied
    
    ----------------------------------------
    Cleaning up...
    Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-TimZHe/warcprox/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-hWq6DN-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-TimZHe/warcprox
    Storing debug log for failure in /home/warc_librarian/.pip/pip.log
    warc_librarian@acstorage3334:~ $ uname -a
    Linux acstorage3334 4.4.34-v7+ #930 SMP Wed Nov 23 15:20:41 GMT 2016 armv7l GNU/Linux
    warc_librarian@acstorage3334:~ $ date
    Wed Feb  8 22:17:46 EET 2017
    warc_librarian@acstorage3334:~ $

**Comment by nlevitt** [comment]
You would have the same problem with any python package. You could try `pip install warcprox --prefix=...`, or use a virtualenv.
