### ISSUE TITLE
Warcprox Playback

### ISSUE THREAD

**Issue by johanneskiesel** [internetarchive/warcprox#29]
I was looking for a possibility to replay warc contents stored by warcprox and found the playback functionality of warcprox quite useful. However, it seems to not work.

Even when I just use `warcprox --playback-port 8001` the program will fail with
`__init__() got an unexpected keyword argument 'options'` from `main.py, line 215`.

It is enough to remove the superfluous parameters to the PlaybackIndexDb (remove `options=options`) and PlaybackProxy (remove `server_address=(args.address, args.playback_port)` and `warcs_dir=args.directory`) constructors from the main.py to get it to work.

**Comment by nlevitt** [comment]
Thanks for the report @johanneskiesel. 7e55568 should fix your issue. (The playback feature is crufty, barely maintained at all. The main thing holding me back is that the automated tests use it extensively.)
